[project]
name = 'Utility-Bill-Management-and-Energy-Monitoring-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.billing-manager]
path = 'contracts/billing-manager.clar'
clarity_version = 2
epoch = 2.5

[contracts.conservation-goals]
path = 'contracts/conservation-goals.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
